### ISSUE TITLE
Object is not a constructor(evaluating 'new _RNSFSpeechRecognizer.default()')

### ISSUE THREAD

**Issue by nileshprajapati007444** [eralpkaraduman/react-native-sfspeechrecognizer-demo#1]
![Screenshot 2019-05-27 at 2 23 39 PM](https://user-images.githubusercontent.com/48590406/58408322-36389c80-808b-11e9-86ad-ea483181453b.png)

**Comment by eralpkaraduman** [comment]
Hi, it seems to be that you are running on android emulator.
Unfortunately android is not supported.
`SFSpeechRecognizer` is a iOS specific toolkit
